### ISSUE TITLE
Show manpage for a word under cursor

### ISSUE THREAD

**Issue by AlekSi** [apophys/SublimeManpage#8]
Hello,

Thank you for a useful plugin. I have an idea how to make it even more useful. How about to show a page for a word under cursor? It would be very useful for C programmer.

**Comment by crazybyte** [comment]
@apophys May I work on this feature (asking so that I won't get in your way)? Thank you!

**Comment by apophys** [comment]
Hi,

how would you propose to do that?

The first thing I came up with is to put the word under the cursor to the form with the option to rewrite the string or accept it directly.

@crazybyte sure :)

Thanks guys for new ideas :+1:

**Comment by AlekSi** [comment]
If user presses hotkey and there is a word under cursor, just show manpage, without asking user to hit enter to submit the form. If you think it will break something, make an option in config or use separate hotkey. Personally, I don't see a use-case for current behavior.

**Comment by crazybyte** [comment]
Hi guys!
@AlekSi I implemented the feature you requested. Now the plugin works the following way: 
If you press ctrl/super+alt+m it shows the panel where you can type in a word and it will search for that man page (basic default behaviour that worked until now).
If you put the cursor under a word in the current view and press ctrl/super+alt+w then it will find the requested man page using the word under cursor (as requested).
I didn't use the default shortcut keys because I didn't want to break the earlier behaviour implemented by the plugin. Please test it and if you have suggestions regarding the new feature or the shortcut (perhaps what combination I choose isn't the best one) feel free to comment or open up a new issue.
If the feature isn't pulled in by the time you want to test it please temporarily head to https://github.com/crazybyte/SublimeManpage and clone the repo into your ~/.config/sublime-text-2/Packages/ folder as SublimeManpage (I'm sorry but I don't know the corresponding folder on MacOSX). You should already have a folder named SublimeManpage in your packages folder, you can rename it so that you will be able to switch between versions easily. @AlekSi thank you for the feature request/new idea, I hope that you will find it useful. 
@apophys could you please merge the pull request that I will send you into the repository, it contains the implementation of the feature requested by @AlekSi. I apologize, I recently discovered that I managed to make a bit of a mess in the commit graph using merge so from now on I will using only rebase so that the revision graph will have a normal/natural flow. Sorry for that (I only recently started using git at it's full potential and it shows). Thank you.
@apophys @AlekSi a Merry Christmas to both of you!

P.S. I something is wrong with how I implemented the feature I'm open to suggestions to improve it. Thank you!

**Comment by apophys** [comment]
The code looks good. I'll wait for any input from @AlekSi and then push the code to the package control.

**Comment by AlekSi** [comment]
On Mac it's `~/Library/Application Support/Sublime Text 2/Packages/SublimeManpage`.
Looks like Default.sublime-commands wasn't updated.
Also created new issue #10.

**Comment by crazybyte** [comment]
Hi @AlekSi 

Yes, I forgot to do that. I will solve it tonight. Thank you!

**Comment by apophys** [comment]
Command added to palette in 250e35d.

**Comment by crazybyte** [comment]
Hi @apophys,

After you pushed the modification I remembered that I made the same modification on my machine only forgot to push it. Nice isn't it? :) I want to ask you want do you think can we do with the other related issue (multiple choices for the same keyword). I think this doesn't have an easy answer and it would over complicate the plugin. What do you think? Thank you and sorry for my absent mindedness.

P.S. Could I somehow contact you on mail, I would need an advice on a matter with a plugin I created.

Best regards,
crazybyte

**Comment by apophys** [comment]
Hi,

right now I'm trying one idea for the other issue, so far no good (well, after 5 minutes...).

An email can be found on my profile.
